In [16]:
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Decluttered Drive/[06] Learning/[02]Data-Science/data-google-colab/feature-engineering-campusx/customer.csv')

In [5]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 2:4], df.iloc[:, -1], test_size=0.2)

In [6]:
X_train

review education
15     Poor        UG
1      Poor        UG
28     Poor    School
12     Poor    School
2      Good        PG
10     Good        UG
24  Average        PG
13  Average    School
49     Good        UG
46     Poor        PG
19     Poor        PG
9      Good        UG
5   Average    School
33     Good        PG
30  Average        UG
11     Good        UG
23     Good    School
36     Good        UG
38     Good    School
29  Average        UG
3      Good        PG
47     Good        PG
22     Poor        PG
25     Good    School
44  Average        UG
32  Average        UG
41     Good        PG
18     Good    School
8   Average        UG
14     Poor        PG
45     Poor        PG
0   Average    School
27     Poor        PG
20  Average    School
6      Good    School
26     Poor        PG
4   Average        UG
21  Average        PG
7      Poor    School
16     Poor        UG

In [7]:
oe= OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [8]:
X_train=oe.fit_transform(X_train)
X_test= oe.transform(X_test)

In [9]:
X_train

array([[0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [0., 1.]])

In [11]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [12]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [15]:
oe.n_features_in_

2

In [17]:
oe.inverse_transform(np.array([0,2]).reshape(1,2))

array([['Poor', 'PG']], dtype=object)

In [18]:
oe= OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']],
                   handle_unknown='use_encoded_value',
                   unknown_value=-1)

In [34]:
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2], dtype=object).T

In [35]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [36]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [37]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [39]:
enc = OrdinalEncoder(min_frequency=3).fit(X)

In [40]:
enc.infrequent_categories_

[array(['horse'], dtype=object)]

In [ ]:
encoder= OrdinalEncoder(encoded_missing_value=np.nan)

# Label Encoder

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le=LabelEncoder()

# One Hot Encoding

In [12]:
pip install numpy --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 45.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xgboost 2.1.0 requires nvidia-nccl-cu12; platform_system == "Linux" and platform_machine != "aarch64", which is not installed.
accelerate 0.32.1 requires numpy<2.0.0,>=1.17, but you have numpy 2.0.1 which is incompatible.
albucore 0.0.12 requires numpy<2,>=1.24.4, but you have numpy 2.0.1 which is incompatible.
arviz 0.18.0 requires numpy<2.0,>=1.23.0, but you have numpy 2.0.1 which is incompatible.
cudf-cu12 24.4.1 requires numpy<2.0a0,>=1.23, but you have numpy 2.0.1 which is incompatible.
cupy-cuda12x 12.2.

In [1]:
import pandas as pd
import numpy as np

In [6]:
cars=pd.read_csv("/content/drive/MyDrive/Decluttered Drive/[06] Learning/[02]Data-Science/data-google-colab/feature-engineering-campusx/cars.csv").drop(columns=['km_driven', 'owner'])

In [7]:
X = cars.iloc[:,0:2]
y = cars.iloc[:,-1]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
ohe = OneHotEncoder()

In [19]:
ohe.fit_transform(X_train)


<6502x72 sparse matrix of type '<class 'numpy.float64'>'
	with 234072 stored elements in Compressed Sparse Row format>

In [20]:
X_train= ohe.fit_transform(X_train).toarray()

In [21]:
X_train.shape

(6502, 72)

(6502, 72)

In [22]:
ohe.categories_

[array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.])]

In [26]:
X_train.n_features_in_

AttributeError: 'numpy.ndarray' object has no attribute 'n_features_in_'

In [19]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [20]:
pd.DataFrame(ohe.fit_transform(X_train),columns=ohe.get_feature_names_out())

x0_0  x0_1  x1_0  x1_1  x2_0  x2_1  x3_0  x3_1  x4_0  x4_1  ...  x31_0  \
0        1     0     1     0     1     0     1     0     1     0  ...      1   
1        1     0     1     0     1     0     1     0     1     0  ...      1   
2        1     0     1     0     1     0     1     0     1     0  ...      1   
3        1     0     1     0     1     0     1     0     1     0  ...      1   
4        1     0     1     0     1     0     1     0     1     0  ...      1   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
6497     1     0     1     0     1     0     1     0     1     0  ...      1   
6498     1     0     1     0     1     0     1     0     1     0  ...      1   
6499     1     0     1     0     1     0     1     0     1     0  ...      1   
6500     1     0     1     0     1     0     1     0     1     0  ...      1   
6501     1     0     1     0     1     0     1     0     1     0  ...      1   

      x31_1  x32_0  x32_1  x33_0  x33_1  x34_0  x34_1  x35_0  x35_1  
0         0      1      0      1      0      1      0      0      1  
1         0      1      0      1      0      1      0      0      1  
2         0      1      0      0      1      1      0      1      0  
3         0      1      0      0      1      1      0      1      0  
4         0      1      0      1      0      1      0      0      1  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  
6497      0      1      0      0      1      1      0      1      0  
6498      0      1      0      0      1      1      0      1      0  
6499      0      1      0      1      0      1      0      0      1  
6500      0      1      0      0      1      1      0      1      0  
6501      0      1      0      1      0      1      0      0      1  

[6502 rows x 72 columns]

# Target Column encoding